%{?!ros_distro:%global ros_distro lyrical}
%global pkg_name mbf_abstract_core
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

Name:           ros-lyrical-mbf-abstract-core
Version:        1.2.1
Release:        1%{?dist}
Summary:        ROS %{pkg_name} package

License:        BSD-3-Clause
URL:            http://github.com/naturerobots/move_base_flex
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  bloom-rpm-macros
BuildRequires:  cmake

%{?bloom_package}

%description
This package provides common interfaces for navigation specific robot actions.
It contains the AbstractPlanner, AbstractController and AbstractRecovery plugin
interfaces. This interfaces have to be implemented by the plugins to make the
plugin available for Move Base Flex. The abstract classes provides a meaningful
interface enabling the planners, controllers and recovery behaviors to return
information, e.g. why something went wrong. Derivided interfaces can, for
example, provide methods to initialize the planner, controller or recovery with
map representations like costmap_2d, grid_map or other representations.


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Provides:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-runtime%{?_isa} = %{version}-%{release}

%description devel
This package provides common interfaces for navigation specific robot actions.
It contains the AbstractPlanner, AbstractController and AbstractRecovery plugin
interfaces. This interfaces have to be implemented by the plugins to make the
plugin available for Move Base Flex. The abstract classes provides a meaningful
interface enabling the planners, controllers and recovery behaviors to return
information, e.g. why something went wrong. Derivided interfaces can, for
example, provide methods to initialize the planner, controller or recovery with
map representations like costmap_2d, grid_map or other representations.


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
This package provides common interfaces for navigation specific robot actions.
It contains the AbstractPlanner, AbstractController and AbstractRecovery plugin
interfaces. This interfaces have to be implemented by the plugins to make the
plugin available for Move Base Flex. The abstract classes provides a meaningful
interface enabling the planners, controllers and recovery behaviors to return
information, e.g. why something went wrong. Derivided interfaces can, for
example, provide methods to initialize the planner, controller or recovery with
map representations like costmap_2d, grid_map or other representations.


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires


%build
%cmake \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="%{bloom_prefix}" \
    -DAMENT_PREFIX_PATH="%{bloom_prefix}" \
    -DCMAKE_PREFIX_PATH="%{bloom_prefix}" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif

%cmake3_build


%install
%cmake_install


%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C %{__cmake_builddir} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
CTEST_OUTPUT_ON_FAILURE=1 \
    %cmake_build $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%{bloom_prefix}


%changelog
* Thu Jul 23 2026 Alexander Mock <alexander.mock@naturerobots.com> - 1.2.1-1
- Autogenerated by Bloom
