<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rviz_mbf_plugins</name>
  <version>1.2.1</version>
  <description>
    Contains rviz plugins for interacting with move base flex.
  </description>
  
  <maintainer email="alexander.mock@naturerobots.com">Alexander Mock</maintainer>
  <maintainer email="georg.john@naturerobots.com">Georg John</maintainer>
  <license>BSD-3-Clause</license>

  <url>http://github.com/naturerobots/move_base_flex</url>
  <author email="matthias.holoch@naturerobots.com">Matthias Holoch</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_action</depend>
  <depend>pluginlib</depend>
  <depend>mbf_msgs</depend>
  <depend>rviz_common</depend>
  <depend>geometry_msgs</depend>

  <!-- From humble, we cannot resolve the version-less keys -->
  <build_depend condition="$ROS_DISTRO == humble">qtbase5-dev</build_depend>
  <build_export_depend condition="$ROS_DISTRO == humble">qtbase5-dev</build_export_depend>
  <exec_depend condition="$ROS_DISTRO == humble">libqt5-widgets</exec_depend>
  <exec_depend condition="$ROS_DISTRO == humble">libqt5-gui</exec_depend>
  <exec_depend condition="$ROS_DISTRO == humble">libqt5-core</exec_depend>

  <!-- From > humble, we can the generic versions -->
  <build_depend condition="$ROS_DISTRO != humble">qt-base-dev</build_depend>
  <build_export_depend condition="$ROS_DISTRO != humble">qt-base-dev</build_export_depend>
  <exec_depend condition="$ROS_DISTRO != humble">libqtwidgets</exec_depend>
  <exec_depend condition="$ROS_DISTRO != humble">libqtgui</exec_depend>
  <exec_depend condition="$ROS_DISTRO != humble">libqtcore</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
